### ISSUE TITLE
Only one wheel working for Lego Boost

### ISSUE THREAD

**Issue by afustePTC** [ptcrealitylab/vuforia-spatial-basic-interfaces-addon#14]
After turning on LegoHub in Manage Hardware Interfaces, legoHub_1 Object was added to Object Configuration tab in Vuforia Spatial Edge Server.
I’ve added a slider in Vuforia Spatial Toolbox and connected it to a node of Motor(s) but somehow I was only able to control right wheel of lego boost

**Comment by realityLabDiscourseUser** [comment]
This issue has been mentioned on **Vuforia Spatial Toolbox Community**. There might be relevant details there:

https://forum.spatialtoolbox.vuforia.com/t/how-do-i-spin-both-wheels-of-lego-boost-using-legohub/92/3
